[package]
name = "buildtime-helpers"
version = { workspace = true }
edition  = { workspace = true }
license  = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
serde_json = { workspace = true }
cargo_metadata = { workspace = true }

[dev-dependencies]
toml = { workspace = true}

[lints]
workspace = true
